### ISSUE TITLE
Can't set user pin after update to RTM.8

### ISSUE THREAD

**Issue by gvintux** [Nitrokey/nitrokey-start-firmware#30]
Hello, I've updated my nitrokey start to RTM.8
I can change admin pin to 14-digit sequence, but can't do that for user pin.
Here is the result, but gpg --card-edit says that 

`
Error changing the PIN: Conditions of use not satisfied
`

```
Device: 
    Vendor: Nitrokey
   Product: Nitrokey Start
    Serial: FSIJ-1.2.15-67094445
  Revision: RTM.8
    Config: NITROKEY_START:dfu=no:debug=no:pinpad=no:certdo=yes:factory_reset=yes
       Sys: 3.0
```
